### ISSUE TITLE
ERROR UPDATING DATABASE

### ISSUE THREAD

**Issue by criestlav** [toolswatch/vFeed#47]
Hi, i am using vfeed on Kali Linux and i am trying to update using: python ./vfeedcli.py --update but it reports to me:

python vfeedcli.py --update
[+] Checking connectivity to http://www.toolswatch.org/vfeed/
[+] New install. Downloading the Correlated Vulnerability Database.
[+] Receiving 5709824 out of 45563168 Bytes of vfeed.db.tgz ( 13 %)Traceback (most recent call last):
  File "vfeedcli.py", line 40, in <module>
    Update().update()
  File "/home/criestlav/Downloads/vFeed-master/lib/core/update.py", line 34, in update
    self.download(self.remote_db)
  File "/home/criestlav/Downloads/vFeed-master/lib/core/update.py", line 63, in download
    self.buffer = self.u.read(self.block_sz)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/httplib.py", line 561, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
socket.error: [Errno 104] Connection reset by peer

What does it mean?

Thank you a lot!!

**Comment by toolswatch** [comment]
Not an issue. criestlav fixed himself because he was using the wrong version of SQLite.
