### ISSUE TITLE
Search when vfeed.db is missing

### ISSUE THREAD

**Issue by toolswatch** [toolswatch/vFeed#49]
WARNING - vfeed.db is missing.
[+] Querying information for daktronics ...
Traceback (most recent call last):
  File "./vfeedcli.py", line 38, in <module>
    Search(args.search)
  File "/Users/dev/Documents/vFeed/test/vFeed/lib/core/search.py", line 18, in **init**
    self.detect_entry()
  File "/Users/dev/Documents/vFeed/test/vFeed/lib/core/search.py", line 38, in detect_entry
    self.search_summary()
  File "/Users/dev/Documents/vFeed/test/vFeed/lib/core/search.py", line 162, in search_summary
    ('%' + self.entry + '%',))
sqlite3.OperationalError: no such table: nvd_db

It will be fixed

**Comment by toolswatch** [comment]
Fixed
